woowacourse-teams/2024-bang-ggood

- frontend/src/components/checklist/CheckListAnswer.tsx
- frontend/src/components/checklist/ChecklistCategory.tsx
- frontend/src/components/checklist/ChecklistQuestion.tsx
- frontend/src/pages/SaveCheckListPage.tsx
> design: 마진 및 라인 하이트 수정

- frontend/src/App.tsx
- frontend/src/Router.tsx
- frontend/src/components/Check.tsx
- frontend/src/components/Header.tsx
- frontend/src/components/HeaderWithLogo.tsx
- frontend/src/components/checklist/CheckListAnswer.tsx
- frontend/src/components/checklist/ChecklistCategory.tsx
- frontend/src/components/checklist/ChecklistQuestion.tsx
- frontend/src/pages/ChecklistPage.tsx
- frontend/src/pages/SaveCheckListPage.tsx
- frontend/src/styles/reset.ts
- frontend/src/styles/theme.ts
> 디자인 시스템을 설정한다. 

- frontend/.storybook/global.ts
- frontend/.storybook/preview.tsx
- frontend/src/styles/theme.ts
- 없음
스토리북용 미리 자동적용되는 global 스타일링 따로 설정
일단은 회색바탕에 흰 화면했는데.
스타일 좀 더 예쁘게해도 됨
(변경되더라도 바탕이랑 화면은 구분되었으면좋겠음)
참고스샷
> storybook 기본 global 스타일링을 설정한다

- frontend/src/components/badge/Badge.stories.tsx
- frontend/src/components/badge/Badge.tsx
- frontend/src/components/button/Button.tsx
- #19 
- 뱃지 공용 컴포넌트를 추가했습니다. 
x
x
> 배지 공용 컴포넌트를 추가한다. 

- .github/workflows/backend-cd.yml
- .github/workflows/backend-ci.yml
- #4 
- main, dev 브랜치에 pr이 생성될 경우 ci를 진행한다.
- main, dev 브랜치에 pr이 머지될 경우 cd를 진행한다.
- 관련 블로그글 작성 예정😀
> 백엔드 CI/CD 설정을 추가한다.

- .github/workflows/backend-cd.yml
- #42
백엔드 CD 설정 오류를 수정하고 성공하는 CD 스크립트를 작성하였다.
> 백엔드 CD 설정 오류를 수정한다.

- .github/workflows/storybook.yml
- #32 
- CICD 루트 frontend 로 변경
> 스토리북 CICD 작업 브랜치 수정

- frontend/src/components/Input/Input.stories.tsx
- frontend/src/components/Input/Input.tsx
> 공용 Input 컴포넌트를 구현한다.

- .github/workflows/storybook.yml
> 스토리북 배포 링크 코멘트로 추가되게 작업한다. 

- .github/workflows/storybook.yml
- 직전 closed된 PR이 정상작동하지 않아, 에러메시지확인후 id를 추가.
> 크로마틱 배포링크 comment on PR이 작동되게 정정

- backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoriesReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
- #46
- 카테고리 조회 기능을 구현했습니다.
- 테스트 코드 수정되거나 추가할 부분 없는지 확인해주세요.
> 카테고리 조회 기능을 구현한다.

- frontend/src/components/common/layout/Layout.tsx
- frontend/src/styles/global.ts
- 
- 공통 레이아웃 컴포넌트 제작 
- 사용방법 
```tsx
<>
<Header />
<Layout>
<div style={{ width: '100%', height: '50px', backgroundColor: 'red' }}> 안녕</div>
</Layout>
</>
```
위 코드와 같이 layout 내부에 children 으로 컨텐츠를 넣으시면 됩니다. 
이외 헤더나 푸터는 외부에서 선언하시면 됩니다.
> 레이아웃 컴포넌트 제작한다. 

- .github/workflows/storybook.yml
> chromatic comment on PR을 설정한다

- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Badge.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> 뱃지 도메인을 추가한다.

- frontend/src/Router.tsx
- frontend/src/components/common/FormField/FormField.stories.tsx
- frontend/src/components/common/FormField/FormField.tsx
- frontend/src/components/common/Input/Input.tsx
- frontend/src/hooks/useInput.ts
- frontend/src/pages/NewChecklistBasicInfoTemplate.tsx
- frontend/src/types/room.ts
- #86 
- 외형은 바뀌지않았으므로 스크린샷은 생략합니다.
> 새 체크리스트 기본정보 페이지를 리팩터링한다.

- .github/workflows/backend-cd.yml
> cd 오류를 해결한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
> CORS 오류를 해결한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> Lazy Initialization 예외를 해결한다.

- frontend/package.json
- frontend/src/pages/CategoryChoosePage.tsx
- frontend/webpack.config.js
#124 
프론트 프로젝트를 빌드해서 배포를 완료한다. 중간에 나는 에러를 해결한다.
> build 시 에러가 발생하는 문제를 해결한다.

- frontend/src/components/ChecklistList/CompareBanner.tsx
- frontend/src/components/NewChecklist/ChecklistCategory.tsx
- frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.test.tsx
- frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
- frontend/src/hooks/useChecklistAnswer.ts
- frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
- frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
- frontend/webpack.config.js
- #127 
- 체크리스트 탭을 넘어가면 감정 선택지가 리셋되는 에러를 수정하였습니다.
> 체크리스트 선택지 저장 못했던 에러 수정하고 체크리스트 답변에 대한 훅으로 리팩토링한다. 

- frontend/src/Router.tsx
- frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
- frontend/src/components/RoomCompare/CompareCard.tsx
- frontend/src/components/RoomCompare/CompareItem.tsx
- frontend/src/components/common/Button/FloatingButton.tsx
- frontend/src/components/common/Footer/Footer.stories.tsx
- frontend/src/components/common/Footer/Footer.tsx
- frontend/src/components/common/Header/Header.tsx
- frontend/src/components/common/layout/Layout.tsx
- frontend/src/mocks/fixtures/checklistList.ts
- frontend/src/mocks/fixtures/roomsForCompare.ts
- frontend/src/pages/CategoryChoosePage.tsx
- frontend/src/pages/ChecklistListPage.tsx
- frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
- frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
- frontend/src/pages/NotFound.tsx
- frontend/src/types/room.ts
- frontend/src/utils/calcEmotions.ts
- #127 
- 체크리스트 옵션 선택 페이지에서 버튼을 눌렀을 때 넘어가지 않는 에러
- 체크리스트 리스트가 밑으로 내려가지 않는 에러
- 리스트 페이지가 밑으로 내려가는 에러 (탭 고정x)
- 플로팅 버튼 위치 에러 
- 푸터가 밑에 붙어있지 않는 에러
- 푸터 매칭이 안되는 에러 
- 하단 탭을 눌렀을 때 나는 페이지 에러 -> 404 페이지 작성 
- 방 비교 페이지 height 에러 
- 타입 선언된 걸 바꾸기 전에 어떤 페이지에서 사용 중인지 확인 후 변경해주시면 좋을거 같습니다. 
roomName 과 같은 경우 타입 선언 변경이 얼마나 필요한지 확인 후 post 하는 곳에서만 name 을 사용하는 편이 기회비용상 더 좋을거 같습니다. 
현재 잘못된 변경으로 인해 생긴 에러는 모두 수정해놨습니다만 돌아가는 다른 코드를 변경할 때는 최대한 확인 후 변경해주시면 좋을거 같습니다. 
x
> 1차 스프린트 페이지내에 에러를 수정한다. 

- frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
- frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
- frontend/src/types/room.ts
- #132 
- roomName 과 name 이 혼돈되어 전달되는 사태를 해결하기 위해 interface 에 더미로 name 옵션을 추가했습니다. 
- TODO 로 roomName 이슈라고 달아놓았으니 이후 수정 시 확인해주시면 될거 같습니다.
> roomName 이슈를 해결한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
-  #134 
- 여러 카테고리에 중복으로 들어있는 질문을 올바르게 수정한다.
- 질문 조회 시 순서가 정렬되어 조회된다.
> 질문 목록 조회 시 질문 순서, 목록이 잘못 조회되는 문제를 해결한다.

- frontend/src/hooks/useChecklistAnswer.ts
- frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
- frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
- #146
체크리스트 데이터가 안 태워지는 에러를 수정한다.
> fix: 체크리스트 저장 버그 수정

- frontend/src/components/FooterDefault.tsx
- frontend/src/pages/ChecklistListPage.tsx
- #162 
- 반복사용되는 5~6줄의 Footer 공통사항을 FooterDefault로 미리 작성해두고 거기에 의존하게 하였습니다.
- 컴포넌트 사용하던 측에도 반영했음.
웬만한 사용처에서는 FooterDefault로 import해서 한줄 쓰시면 됩니다.
```javascript
<FooterDefault / >
```
> [FE] 반복사용되는 footerDefault를 더쉽게 사용한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/request/CategoryPriorityCreateRequest.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/CategoriesReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/CategoryQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/CategoryReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/WrittenCategoryQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/ChecklistQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/UserChecklistsPreviewResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/WrittenChecklistResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistCreateRequest.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistInfo.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/QuestionCreateRequest.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/BadgeResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryScoreReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistComparisonReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistsComparisonReadResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/QuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistsPreviewResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/WrittenChecklistResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/WrittenQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/request/RoomCreateRequest.java
- backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/WrittenRoomResponse.java
- backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
- #168 
- 카테고리 조회 API
- 카테고리 우선순위 저장 API
> [BE] 카테고리 조회 & 우선순위 저장 API를 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Badge.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/BadgeResponse.java
- #200 
- Badge 도메인에 아이디 추가
- Response 내 BadgeId 추가
> [BE] 뱃지 아이디를 추가한다. 

- frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
- frontend/src/components/common/FaceMark/FaceIcon.tsx
- frontend/src/constants/emotion.ts
- frontend/src/hooks/useChecklistAnswer.test.ts
- frontend/src/hooks/useChecklistAnswer.ts
- frontend/src/mocks/fixtures/checklistDetail.ts
- frontend/src/pages/ChecklistDetailPage.tsx
- frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
- frontend/src/store/useChecklistStore.ts
- frontend/src/types/checklist.ts
- frontend/src/types/emotionAnswer.ts
- frontend/src/types/room.ts
-  #228 
name, roomName 공존하던 것을 정리
Emotion에서 grade:null로 표현하던 걸 "NONE"으로 사용하게 변경
이에 따라 hooks쪽 구현과 테스트코드 반영.
밑에 코드인용 확인해주세요
> [FE] 체크리스트 API 변경에 맞게 interface타입을 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> [BE] 쿠키설정을 추가한다.

- frontend/src/components/NewChecklist/NewChecklistContent.tsx
- frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
- frontend/src/components/NewChecklist/useRoomStructure.tsx
- frontend/src/components/RoomCompare/CompareCard.tsx
- frontend/src/components/_common/Badge/Badge.stories.tsx
- frontend/src/components/_common/Badge/Badge.tsx
- frontend/src/hooks/useInputs.ts
- frontend/src/mocks/fixtures/checklistDetail.ts
- frontend/src/pages/CategoryChoosePage.tsx
- frontend/src/pages/NewChecklistPage.tsx
- frontend/src/types/room.ts
- #246 
- 방 기본정보 상태연결 & POST API 정상 동작 확인
- 아까 구두 전달 한대로 Badge 공통 컴포넌트 HTML 속성명과 충돌해서 type->size로 명칭변경
> [FE] 기본정보 페이지 상태연결을 완료한다.

- backend/bang-ggood/src/main/resources/data.sql
> [BE] 유저를 저장하는 과정에서 발생하는 에러를 해결한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryCustomChecklistQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryCustomChecklistQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #226 
<커밋 범위>
https://github.com/woowacourse-teams/2024-bang-ggood/pull/263/commits/1785ca98a6760c0ffe3cdacbe63d0cc156299395
- 삭제시 논리적 삭제되도록 수정했습니다.
> [BE] 사용자 체크리스트 리스트 API에 논리적 삭제를 적용한다.

- frontend/src/pages/ChecklistListPage.tsx
- frontend/src/pages/RoomCompareSelectPage.tsx
- frontend/src/store/useRoomCompareStore.test.ts
- frontend/src/store/useRoomCompareStore.ts
> [FE] 체크리스트 비교 선택페이지를 비교페이지와 연결한다.

- frontend/.gitignore
- frontend/src/apis/url.ts
- frontend/src/components/RoomCompare/CompareCard.tsx
- frontend/src/components/_common/layout/Layout.tsx
- frontend/src/pages/ChecklistListPage.tsx
- frontend/src/pages/RoomComparePage.tsx
- frontend/src/pages/RoomCompareSelectPage.tsx
- frontend/src/router.tsx
- frontend/src/store/useRoomCompareStore.test.ts
- frontend/src/store/useRoomCompareStore.ts
- frontend/src/types/checklist.ts
- frontend/webpack.config.js
- #261 
- 방 선택 페이지 라우트 지정
- 방 비교 페이지 api 확인
> [FE] 페이지 라우트를 정리하고 방 비교 페이지 API 를 확인한다. 

- frontend/index.html
> [FE] Google Analytics를 적용한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/CustomChecklistQuestionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/config/WebMvcConfig.java
- backend/bang-ggood/src/main/resources/schema.sql
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistQuestionTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistRankTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
> [BE] 코드 스타일을 정리한다.

- frontend/src/apis/checklist.ts
- frontend/src/pages/NewChecklistPage.tsx
- #291 
- 방 작성 post api 버그 수정 
- 추가 이전에 페이지 이동 버그 막음
> [FE] 3차 데모데이 배포 사이트의 버그를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistLike.java
> [BE] 체크리스트 좋아요 도메인을 추가한다.

- frontend/src/constants/queryKeys.ts
- frontend/src/constants/system.ts
- frontend/src/hooks/query/useAddChecklistQuery.ts
- frontend/src/hooks/query/useDeleteChecklistQuery.ts
- frontend/src/hooks/query/useGetChecklistListQuery.ts
- frontend/src/hooks/query/useRefetchGetChecklistList.ts
- frontend/src/pages/ChecklistDetailPage.tsx
- frontend/src/pages/ChecklistListPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
- #305 
- 리스트 데이터를 받아오는 것을 리액트 쿼리를 사용해 리팩토링
- mutation 으로 관리하여 변경시 리스트 데이터를 새로 받아올 수 있게 작업
- 체크리스트 데이터 추가
- 체크리스트 데이터 삭제
> [FE] 리스트 상태 관리를 react-query 를 사용하여 전역으로 관리한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
> [BE] 체크리스트 작성 시 메모에 관해 NPE 뜨는 오류를 수정한다.

- frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
- #339 
맨 아래의 두 폼에서 에러메시지가 표출되는 현상을 해결한다
> [FE] 맨 아래의 두 폼에서 에러메시지가 표출되는 현상을 해결한다

- frontend/src/components/NewChecklist/NewChecklistFormField.tsx
- frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
> [FE] 기본정보 페이지의 라벨에 평수를 추가한다

- frontend/src/components/NewChecklist/NewChecklistContent.tsx
- frontend/src/components/NewChecklist/SummaryModal/SummaryModal.tsx
- frontend/src/pages/NewChecklistPage.tsx
- frontend/src/store/checklistRoomInfoStore.test.ts
- frontend/src/store/checklistRoomInfoStore.ts
- #345 
- 한줄평 작성 모달 
- `저장` 버튼 클릭 시 한줄평 작성 모달이 열리고 저장되면 체크리스트가 저장됩니다.
> [FE] 한줄평 기능을 추가한다. 

- frontend/src/apis/checklist.ts
- frontend/src/mocks/fixtures/dummyChecklist.ts
- frontend/src/pages/LoginPage.tsx
- frontend/src/store/checklistRoomInfoStore.ts
- [FE] 사용자가 처음 방끗을 사용할 때 디폴트 체크리스트를 보여준다.
> [FE] 사용자가 처음 방끗을 사용할 때 디폴트 체크리스트를 보여준다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
- #354 
- 기획 수정으로 추가된 데이터 반영했습니다.
- JSON에서 createdAt 키를 room내부로 이동시켰습니다.
> [BE] 체크리스트 조회 API를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
- #361 
- 질문 조회시 카테고리 이모지 제외하고 전달하도록 수정했습니다.
> [BE] 체크리스트 질문 조회 API를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #313 
- 바뀐 필드에 따라 수정 기능 변경
- user 소유 여부 체크
> [BE] 체크리스트 수정 API를 추가 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #369 
- 삭제하려는 유저가 해당 체크리스트 작성 유저가 맞는지 검증 로직 추가
> [BE] 체크리스트 삭제 API를 추가 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
> [BE] 수정된 옵션 항목을 반영한다.

- .github/workflows/backend-ci.yml
- .github/workflows/backend-dev-cd.yml
- backend/bang-ggood/.gitignore
> [BE] dev, prod, local 설정 파일 분리한다.

- frontend/src/apis/checklist.ts
- frontend/src/components/Answer/AnswerIcon.tsx
- frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
- frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
- frontend/src/constants/routePath.ts
- frontend/src/hooks/query/useGetChecklistDetailQuery.ts
- frontend/src/hooks/useNewChecklistTabs.ts
- frontend/src/pages/EditChecklistPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
- frontend/src/router.tsx
- frontend/src/store/checklistRoomInfoStore.ts
- frontend/src/store/useChecklistStore.ts
- frontend/src/utils/typeFunctions.ts
- #382 
RoomDetail 페이지에서 개별 방정보 불러오는 로직 가져오고
NewChecklistInfo 페이지에서 기본 템플릿만들때 쓰는 상태로직들 + UI 가져오고
둘이 합쳐서 만들었습니다.
POST 날아가는거 확인완료
> [FE] 체크리스트 수정페이지를 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
> [BE] 옵션 목록을 수정한다. 

- backend/bang-ggood/src/main/resources/schema.sql
> [BE] dev-be 브랜치와 dev 브랜치를 병합한다.

- frontend/src/RootLayout.tsx
- frontend/src/components/Auth/AuthGuard.tsx
- frontend/src/components/ChecklistList/ChecklistCard.tsx
- frontend/src/components/Main/ArticleSection.tsx
- frontend/src/components/Main/ChecklistPreviewCard.tsx
- frontend/src/components/Main/ChecklistSection.tsx
- frontend/src/components/NewChecklist/NewChecklistContent.tsx
- frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
- frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
- frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
- frontend/src/components/_common/Tabs/Tab.tsx
- frontend/src/components/_common/Tabs/Tabs.tsx
- frontend/src/components/_common/layout/Layout.tsx
- frontend/src/components/skeleton/Article/SkArticleList.tsx
- frontend/src/components/skeleton/ChecklistList/SkChecklistLst.tsx
- frontend/src/constants/style.ts
- frontend/src/constants/system.ts
- frontend/src/hooks/query/useGetArticleListQuery.ts
- frontend/src/hooks/query/useGetArticleQuery.ts
- frontend/src/hooks/query/useGetChecklistDetailQuery.ts
- frontend/src/hooks/query/useGetChecklistListQuery.ts
- frontend/src/pages/ChecklistListPage.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
- frontend/src/router.tsx
- frontend/src/styles/global.ts
- #383 
- 로그인 후 isLogin 스토리지를 갖는다. 
- 스토리지 없을 시 로그인 페이지로 리다이렉트를 진행 
- 이후 백엔드 회원정보 api 완성시 해당 api 와 연결하여 status 로 재처리할 예정
undefined 확인 처리가 안된 것들을 처리했습니다.
> [FE] 로그인 되지 않았을 경우 OAuth로그인페이지로 route한다. 

- backend/bang-ggood/src/main/resources/schema.sql
> 스키마를 수정한다.

- backend/bang-ggood/src/main/resources/data.sql
- backend/bang-ggood/src/main/resources/schema.sql
> 아티클 스키마를 수정한다.

- backend/bang-ggood/src/main/resources/data.sql
- backend/bang-ggood/src/main/resources/schema.sql
> [BE] dev-be를 dev 브랜치로 병합한다.

- frontend/src/assets/assets.tsx
- frontend/src/assets/icons/dropdown/dropdown-mark.svg
- frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
- frontend/src/components/_common/Dropdown/Dropdown.stories.tsx
- frontend/src/components/_common/Dropdown/Dropdown.tsx
- frontend/src/styles/theme.ts
> [FE] 드롭다운 제어컴포넌트를 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
- backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
> [BE] dev-be 브랜치를 dev로 병합한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
> [BE] 유저 정보 조회 데이터 명을 수정한다.

- backend/bang-ggood/src/main/resources/schema.sql
- backend/bang-ggood/src/test/resources/schema-test.sql
> [BE] 아티클 content 길이를 늘린다.

- backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
- backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceMockTestSupport.java
- #444 
- ActiveProfiles에 test 추가
> [BE] AcceptanceMockTestSupport 파일 ActiveProfiles에 test를 추가한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
- backend/bang-ggood/src/main/resources/schema.sql
- backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceMockTestSupport.java
- backend/bang-ggood/src/test/resources/schema-test.sql
> [BE] dev-be와 dev를 병합한다.

- backend/bang-ggood/src/main/resources/schema.sql
- backend/bang-ggood/src/test/resources/schema-test.sql
> [BE] 아티클 내용 길이를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
- backend/bang-ggood/src/test/java/com/bang_ggood/config/CorsConfigTest.java
- #356 
- allowOrigins 사용하도록 변경
> [BE] CORS 설정시 dev, prod를 분리한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
- backend/bang-ggood/src/test/java/com/bang_ggood/config/CorsConfigTest.java
> [BE] dev-be와 dev 브랜치를 병합한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
- backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
-  #438 
- 유저 정보 조회 시 username을 반환
-
> [BE] 유저 정보 조회 시 username을 반환한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipalArgumentResolver.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
- #405 
- 로그아웃 시 토큰 블랙리스트에 저장
- 임시방편으로 메모리에 블랙리스트를 저장하였습니다. 추후 refresh token을 도입하면 전체적인 수정이 필요하여 간단하게 구현하였습니다.
> [BE] 로그아웃 기능을 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/QuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #466 
- 질문 내부 하이라이트 데이터 저장
- Question 클래스 변경
- 질문 조회시 하이라이트 키워드 함께 전달
QuestionResponse 타입을 record에서 class로 변경했습니다 ‼️
현재 CustomChecklistQuestionResponse, QuestionResponse, SelectedQuestionResponse가 QuestionResponse의 필드를 공유하고 있는데요, Question의 필드가 추가될 때마다 모든 DTO를 변경해줘야하는 것이 불편하게 느껴졌습니다. Question 데이터는 필드 변경될때마다 다른 DTO들이 모두 영향을 받을 것 같아서 연관관계가 강하다고 생각했고 이를 상속으로 풀어서 해결했습니다. Record 사용이 컨벤션이지만 이렇게 필요한 부분은 클래스로 사용해도 괜찮을지 다같이 논의해보면 좋을 것 같아요~
> [BE] 질문 조회시 하이라이트를 함께 전달한다. 

- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
- frontend/src/mocks/fixtures/checklistList.ts
- frontend/src/store/checklistRoomInfoStore.ts
> [FE] N번째 방을 기본입력으로 구현한다

- frontend/package.json
- frontend/webpack.config.js
- frontend/yarn.lock
- #473 
기초적인 번들 코드스플리팅을 적용해서 warning을 해결
(250KB 단위로 스플릿하고 의존성을 캐싱한다.)
sentry 계정 변경 적용. (.env 올려놨습니다.)
> [FE] 기초적인 번들 코드스플리팅을 적용해서 warning을 해결한다.

- frontend/src/constants/oAuth.ts
> [FE] dev 서버 env 설정을 변경한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #485 
selected -> isSelected
> 커스텀 질문 조회 response를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
- #490 
- buildingName, walkingTime, station DTO 추가
> [BE] 체크리스트 리스트 API를 수정한다.

- frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
- frontend/src/components/Main/ChecklistPreviewCard.tsx
- frontend/src/constants/httpErrorMessage.ts
- frontend/src/mocks/fixtures/checklistDetail.ts
- frontend/src/pages/ArticleDetailPage.tsx
- #484 
- 지하철 `역` 텍스트 추가
-  md 다크 모드 사용을 막는다.
> [FE] QA - 지하철 `역` 텍스트 추가 및 md 다크 모드 사용을 막는다. 

- frontend/src/components/_common/FloatingButton/FloatingButton.tsx
- frontend/src/pages/ChecklistListPage.tsx
- #484 
- 체크리스트 리스트 마진 바텀 추가 
- 플로팅 버튼 위치를 조정
> [FE] QA - 체크리스트 리스트 마진 바텀 추가 및 플로팅 버튼 위치를 조정한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> [BE] 로그아웃이 안되는 문제를 해결한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
- #505 
- 체크리스트 조회시 최신순으로 조회하는 기능 구현
> [BE] 체크리스트를 최신순으로 조회한다.

- frontend/src/components/Landing/FirstSection.tsx
- frontend/src/components/MyPage/LogoutModal.tsx
- frontend/src/hooks/query/useLogoutQuery.ts
- frontend/src/pages/ChecklistDetailPage.tsx
- 
[FE] QA - 로그아웃 기능 버그를 수정한다.
> [FE] QA - 로그아웃 기능 버그를 수정한다. 

- frontend/src/components/Landing/FourthSection.tsx
- frontend/src/components/Landing/SecondSection.tsx
- frontend/src/components/Landing/ThirdSection.tsx
- frontend/src/constants/category.ts
- #499 
png 이미지가 엑스박스 뜨는 버그를 해결한다.
> [FE] png 이미지가 엑스박스 뜨는 버그를 해결한다.

- frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
- frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
- frontend/src/constants/options.ts
- frontend/src/utils/typeFunctions.ts
- #484 
- [FE] 디폴트 방 이름 날짜 버그를 수정한다.
> [FE] 디폴트 방 이름 날짜 버그를 수정한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> [BE] 로그아웃이 정상적으로 되지 않는 문제를 해결한다.

- frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
- frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
> [FE] 카카오 지도의 주석 해제한다.

- frontend/src/store/checklistRoomInfoStore.ts
- frontend/src/store/createFormStore.ts
- frontend/webpack.config.js
- #516 
- #484
- kakao맵 env가 안되는 문제 해결
- 방 기본정보를 로컬스토리지로 기억한다.
> [FE] html 내부에서 <%= => 템플릿 구문을 작동하게한다.

- frontend/src/index.tsx
- frontend/src/mocks/handlers/checklist.ts
- frontend/src/pages/EditChecklistPage.tsx
- #484 
체크리스트 수정페이지에서 post이 아닌 put이 날아가게한다.
> [FE] 체크리스트 수정페이지에서 post이 아닌 put이 날아가게한다.

- frontend/src/components/_common/Like/LikeButton.tsx
- #484 
디테일페이지의 좋아요버튼 불일치 버그를 해결한다
> [FE] 디테일페이지의 좋아요버튼 불일치 버그를 해결한다

- frontend/src/components/_common/Like/LikeButton.tsx
- frontend/src/components/_common/Map/RealTimeMap.tsx
- frontend/src/pages/EditChecklistPage.tsx
> [FE] 편집페이지에 메모모달을 추가한다.

- frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
- frontend/src/pages/ChecklistDetailPage.tsx
- 
- [FE] 디테일 페이지 내 `정보없음` 처리 안된 벨류 처리
> [FE] 디테일 페이지 내 `정보없음` 처리 안된 벨류 처리

- frontend/src/components/_common/AlertModal/AlertModal.tsx
- frontend/src/components/_common/Button/Button.tsx
- frontend/src/index.tsx
> [FE] hofix로 버튼 사이즈를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
> [BE] 체크리스트 조회시 관리비를 포함한다.

- frontend/src/components/_common/AlertModal/AlertModal.tsx
- frontend/src/components/_common/Button/Button.tsx
- frontend/src/index.tsx
> [FE] 불필요한 모달 박스 삭제 및 워딩 수정

- frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
> [FE] 자동화 워딩 수정

- frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
- frontend/src/index.tsx
> [FE] hotfix인 자동화 버튼 워딩 수정 및 불필요한 박스를 삭제한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #610 
- Repository 메서드 파라미터를 Long타입으로 변경하고 테스트 코드 통과하도록 수정했습니다.
- 일단 제 부분만 변경해두었는데, 나중에 리팩토링하면서 타입 변경 잘 맞춰줘야 할 것 같습니다!
> [BE] Repository 메서드 타입 Long으로 변경

- frontend/src/apis/fetcher.ts
- frontend/src/constants/httpErrorMessage.ts
- frontend/src/constants/message.ts
- frontend/src/pages/ChecklistCustomPage.tsx
- frontend/src/pages/ChecklistListPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
- frontend/src/routers/router.tsx
- #634 
- 토스트 에러 메세지에 대한 피드백이 나와서 리팩토링 진행했습니다. 
- 토스 UX 라이팅을 참고해서 진행해봤습니다.
> [FE] 토스트 에러 메세지에 UX 라이팅을 접목하여 리팩토링한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
> [BE] 새로운 질문을 추가한다.

- backend/bang-ggood/src/main/resources/schema.sql
- backend/bang-ggood/src/test/resources/schema-test.sql
> [BE] Mysql 문법에 맞게 sql을 고친다.

- backend/bang-ggood/src/main/resources/schema.sql
- backend/bang-ggood/src/test/resources/schema-test.sql
> [BE] dev-be를 dev에 반영한다.

- .github/workflows/backend-prod-cd.yml
> [BE] prod cd 스크립트를 변경한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
- #628 
- 체크리스트 조회시 좋아요 여부를 전달하도록 수정했습니다. 
- 이전 PR에서 TODO로 남겨둔 부분이어서 작업사항이 많지는 않습니다.
> [BE] 체크리스트 조회시 좋아요 여부를 전달하도록 수정한다.

- frontend/src/index.css
- #650
마지막 리뷰에서 fonts폴더로 이동코멘트받아서 반영할때 .css에서 경로수정이 빠져있었어서 올립니다.
> [FE] 폰트 폴더경로변경 한군데 빠졌던 것 반영한다

- .github/workflows/backend-ci.yml
- .github/workflows/backend-dev-cd.yml
- .github/workflows/backend-prod-cd.yml
- #675 
- ci/cd 스크립트내에 read/write yml 파일 생성하는 부분 추가
> [BE] read/write 관련 ci/cd 스크립트를 수정한다.

- backend/bang-ggood/.gitignore
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/datasource/DataSourceConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/datasource/DataSourceRouter.java
- backend/bang-ggood/src/test/java/com/bang_ggood/global/datasource/DataSourceTest.java
> [BE] read/write db 분리

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
> [BE] respository id 타입을 long에서 Long으로 바꾼다.

- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
> [BE] checklistQuestion dirty checking가 안 되는 문제를 해결한다.

- frontend/src/store/checklistRoomInfoStore.ts
- #693 
FE전원과논의후 디폴트값을 현재월로 설정
> [FE] 입주가능월이 0이라서 발생하는 요청에러를 해결한다.

- frontend/src/hooks/useMutateChecklist.ts
- #696 
[FE] 로그인 에러 아닌 일반 에러에도 로그인 유도창이 뜨는 버그를 수정한다.
> [FE] 로그인 에러 아닌 일반 에러에도 로그인 유도창이 뜨는 버그를 수정한다.

- frontend/src/hooks/useMutateChecklist.ts
- frontend/src/store/checklistRoomInfoStore.ts
- frontend/src/styles/reset.ts
- frontend/src/types/room.ts
- #699 
- 모바일에서 터치시 파란박스 css 없앰
- 방구조를 defualt 을 NONE으로 지정하여 버그 해결
> [FE] 방구조 버그를 해결한다.

- frontend/src/pages/ArticleDetailPage.tsx
- #701  
- 아티클 디테일 페이지의 스크롤이 안되는 버그를 수정했습니다.
> [FE] 페이지 스크롤 안되는 버그 수정

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> [BE] 로그아웃이 안되는 오류를 해결한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> [BE] dev 서버에 배포한다

- frontend/src/apis/checklist.ts
- #707 
checklist의 structure NONE일 경우 null로 보내지게 반영한다
> [FE] checklist의 structure NONE일 경우 null로 보내지게 반영한다

- frontend/src/routers/GoogleAnalytics.tsx
- frontend/src/routers/router.tsx
> [FE] Google Analytics를 레이아웃에 넣어 작동되게 한다. 

- frontend/src/routers/GoogleAnalytics.tsx
> [FE] 레이아웃이 두개씩 생기는 버그를 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
- #623 
- 커스텀 체크리스트 카테고리, 질문 조회 구현 방식 Map대신 LIst를 활용해서 구현
구현방식 바꿔봤는데 기존 것보다 괜찮은지 봐주세요!
> [BE] 커스텀 체크리스트 질문 조회 관련 api 구현 방식을 일치시킨다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/OauthPropertiesTest.java
> fix: Redirect Uri 값 저장하는 과정에서 발생하는 에러 해결

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/OauthPropertiesTest.java
> [BE] DEV와 DEV-BE 브랜치를 병합한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> [BE] Location URI를 프론트 기준으로 변경한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> [BE] DEV와 DEV-BE를 병합한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/CorsConfig.java
- #750 
프론트에서 Location에 접근하지 못하는 문제를 해결하고자 설정 정보 추가
```java
configuration.addExposedHeader(HttpHeaders.LOCATION);
```
> [BE] CORS 설정에 exposedHeader를 추가한다.

- frontend/src/components/_common/Like/LikeButton.tsx
- frontend/src/hooks/query/useToggleLikeQuery.ts
- frontend/src/pages/MyPage.tsx
- #733 
- 낙관적 업데이트 실패시 처리 
- 마이페이지에서 로그인 페이지로 이동 처리
> [FE] 좋아요 낙관적 업데이트 수정하여 API 실패 시 상태 롤백 추가한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
- #794 
로케이션 헤더 수정(checklists -> checklist)
> [BE] 로케이션 헤더를 수정한다

- frontend/src/apis/checklist.ts
- frontend/src/apis/url.ts
- frontend/src/hooks/query/useGetChecklistDetailQuery.ts
- frontend/src/mocks/fixtures/checklistDetail.ts
- frontend/src/mocks/fixtures/subway.ts
- frontend/src/mocks/handlers/checklist.ts
- frontend/src/pages/ChecklistDetailPage.tsx
- frontend/src/types/checklist.ts
- #784
- 체크리스트 디테일을 가져오는 api 에서 지하철이 추가되어, 기존에 저희가 지하철을 불러오는 로직을 삭제하고 바뀐 api 를 적용하였습니다.
> [FE] 바뀐 디테일 api 에 맞게 포맷을 수정한다. 

- frontend/src/App.tsx
- frontend/src/assets/assets.tsx
- frontend/src/assets/icons/toast/toast-confirm.svg
- frontend/src/assets/icons/toast/toast-error.svg
- frontend/src/components/_common/Toast/Toast.stories.tsx
- frontend/src/components/_common/Toast/Toast.tsx
- frontend/src/components/_common/Toast/ToastContainer.tsx
- frontend/src/hooks/query/useToggleLikeQuery.ts
- frontend/src/hooks/useMutateChecklist.ts
- frontend/src/hooks/useToast.test.ts
- frontend/src/hooks/useToast.ts
- frontend/src/pages/CategoryChoosePage.tsx
- frontend/src/pages/ChecklistQuestionSelectPage.tsx
- frontend/src/store/useToastStore.ts
- frontend/src/types/toast.ts
> [FE] 토스트 에러 핸들링 리팩토링 및 시나리오 개편을 진행한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> [BE] 토큰 무효화 api를 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieResolver.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/RefreshTokenCheckResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/TokenExistResponse.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
- #792 
- 리프레시 토큰 존재 여부 반환하면서 액세스 토큰도 반환할 수 있게 구현
- 앤드포인트 이름 변경
- DTO 클래스 이름 변경
> [BE] 액세스 토큰 존재 여부를 반환한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- #790
로그아웃을 oauth 뿐만 아니라 local에서도 적용하기 위해 path를 변경하였습니다
> [BE] 로그아웃 path를 변경한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
> [BE] 회원 탈퇴를 구현한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ClientExceptionCode.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/handler/GlobalExceptionHandler.java
- #818 
파라미터 오류 시 에러 메시지를 정상적으로 수정
> [BE] 파라미터 오류 시 에러 메시지를 정상적으로 수정한다

- .github/workflows/backend-prod-cd.yml
> [BE] 무중단 배포 cd 파일을 업데이트 한다.

- .github/workflows/backend-prod-cd.yml
- #837 
deploy2 -> deploy1 의존성 추가
> [BE] 무중단 배포 파일을 업데이트 한다.

- .github/workflows/backend-prod-cd.yml
> [BE] cd 파일 오류를 수정한다

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CategoryRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/QuestionFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/CategoryRepositoryTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
> [BE] dev-be를 dev로 병합한다.

- .github/workflows/backend-prod-cd.yml
- #847 
- prod cd에서 health ceck 응답 학인
> [BE] 무중단 배포에서 health-check 부분을 추가한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/QuestionEntity.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CustomChecklistQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/QuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/SelectedQuestionResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/HighlightRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> [BE] DEV와 DEV-BE를 병합한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> [BE] 지하철 역 조회 시 위도 경도 데이터 오류 수정

- frontend/src/pages/EditChecklistPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
> [FE] 탭 랜더링 실패 오류를 수정한다. 

- frontend/public/index.html
- frontend/src/apis/fetcher.ts
- frontend/src/pages/LandingPage.tsx
- frontend/src/sentry.ts
- frontend/webpack.common.js
- #872 
기존 빌드 방식: 빌드된 모든 파일이 dist/ 내부에 동일 레벨로 관리 
변경된 방식 : 이미지 파일, 폰트 파일들은 static/images, static/fonts 로 파일을 분리해서 관리 
작업한 이유 -> og 커버 작업을 위해 절대경로로 작업하던 중 빌드된 파일이 무분별하게 하나의 폴더로 관리되고 있음을 발견
> [FE] public assets 에러 로그 및 og 커버 버그, 그리고 센트리 작동 안함 이슈를 해결한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
- #879 
- 회원 탈퇴를 할 때 RefreshToken과 AccessToke을 삭제
> [BE] 회원 탈퇴 시 토큰을 삭제한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
- #898 
- 체크리스트 좋아요 필터링 버전 업데이트
> [BE] 체크리스트 좋아요 필터링 버전을 업데이트한다.

- frontend/src/components/ChecklistDetail/ChecklistDetailSection.tsx
- frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
- frontend/src/components/_common/Map/AddressMap.tsx
- frontend/src/hooks/query/useToggleLikeQuery.ts
- frontend/src/mocks/fixtures/checklistDetail.ts
- frontend/src/types/checklist.ts
- #906
디테일 get api 의 v1 의 station 바뀐 포맷 부분을 적용했습니다. 추가적으로 주소가 없을 때 지하철, 지도를 안 보여주는 로직도 추가했습니다.
> [FE] 체크리스트 get api 지하철 포맷 수정한다.

- frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
- frontend/src/components/_common/Header/Header.tsx
- frontend/src/components/_common/Subway/SubwayStations.tsx
- frontend/src/components/_common/Tabs/TabButton.tsx
- frontend/src/components/_common/Tabs/Tabs.tsx
- frontend/src/constants/messages/apiErrorMessage.ts
- frontend/src/hooks/query/useDeleteAccount.ts
- frontend/src/hooks/query/useLogoutQuery.ts
- frontend/src/pages/ChecklistQuestionSelectPage.tsx
- frontend/src/pages/EditChecklistPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
> [FE] QA 진행 후 생긴 버그들을 수정한다.

- frontend/src/components/ChecklistDetail/MemoSection.tsx
- #914
`\n` 을 인식해 여백을 늘리게 하였습니다.
> [FE] 디테일에서 메모가 줄바꿈 되게 수정한다. 

- frontend/src/components/ChecklistQuestionSelect/ChecklistQuestionSelectTabs.tsx
- frontend/src/components/ChecklistQuestionSelect/QuestionListTemplate/QuestionListTemplate.tsx
- frontend/src/components/EditChecklist/ChecklistTab/EditChecklistTab.tsx
- frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
- frontend/src/components/_common/errorBoundary/ChecklistTabSuspense.tsx
- frontend/src/components/skeleton/Main/SkChecklistSection.tsx
- frontend/src/components/skeleton/QuestionSelect/SKQuestionSelectList.tsx
- frontend/src/hooks/useInitialChecklist.ts
- frontend/src/store/useChecklistStore.ts
- frontend/src/utils/isSameCategory.ts
- #917 
문제 상황 요약 
**터지는 에러 문제 : 카테고리 ID: 4 를 찾을 수 없습니다.**
해당 문제는 탭을 생성할 때 모든 질문이 다 체크되어있는지 확인하는 과정에서 스토어가 가지고 있는 카테고리와 전달받은 카테고리를 비교하면서 발생합니다. 
아래 사진을 보시면 첫번째가 api 호출 부분입니다. 받아오는 api 에는 4번이 있습니다. 
그런데 두번째 사진의 스토리지를 보시면 4가 없고 3까지만 있는걸 확인하실 수 있습니다. 
| <img width="1161" alt="스크린샷 2024-10-25 오전 1 25 37" src="https://github.com/user-attachments/assets/375f314f-eeb3-4663-be45-c0130cb60304">  |  <img width="1433" alt="스크린샷 2024-10-25 오전 1 30 13" src="https://github.com/user-attachments/assets/3219d69f-c19d-4854-874b-91a8e4094335">   |
|---------------------------|---------------------------|
이 과정을 체크하고 어떻게 하면 이런 문제가 생길까  시나리오가 짜서 시뮬레이션을 돌려봤습니다. 
예상 시나리오 : 
1. 카테고리가 4개인 상태에서 새 체크리스트를 작성하려고 했다. 
2. 작성 중 완료하지 않고 `뒤로가기 버튼` 을 누르지 않은채 빠져나옴 
3. 이후 새로운 링크 혹은 새로운 디바이스, 혹은 url 이동 등으로 스토어 …
> [FE] 탭이 종종 랜더링되지 않고 터지는 버그를 수정한다.

- frontend/src/components/_common/Like/LikeButton.tsx
- #908
아까 좋아요 이슈랑은 무관한 내용입니다.
엄청빨리누르면 버튼이 반응안하게해뒀었는데 그냥빨리빨리반응하게했습니다.
> [FE] 좋아요를 매우 빨리 누를 때 빨리 변하게 한다.

- frontend/src/pages/NewChecklistPage.tsx
- [FE] 나가기 네이게이트 안되는 오류를 수정한다.
> [FE] 나가기 네이게이트 안되는 오류를 수정한다. 

- frontend/playwright/tests/api/renderTab.spec.ts
- frontend/playwright/tests/mock/postNewChecklist.spec.ts
- frontend/src/components/ChecklistQuestionSelect/ChecklistQuestionSelectTabs.tsx
- frontend/src/components/ChecklistQuestionSelect/QuestionListTemplate/QuestionListTemplate.tsx
- frontend/src/components/EditChecklist/ChecklistContent/EditChecklistContent.tsx
- frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
- frontend/src/components/EditChecklist/ChecklistTab/EditChecklistTab.tsx
- frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
- frontend/src/components/_common/errorBoundary/ChecklistTabSuspense.tsx
- frontend/src/components/skeleton/Main/SkChecklistSection.tsx
- frontend/src/components/skeleton/QuestionSelect/SKQuestionSelectList.tsx
- frontend/src/hooks/useInitialChecklist.ts
- frontend/src/pages/EditChecklistPage.tsx
- frontend/src/pages/NewChecklistPage.tsx
- frontend/src/store/useChecklistStore.ts
- frontend/src/utils/isSameCategory.ts
> [FE] 뒤로가기 에러를 수정한다. 

- backend/bang-ggood/build.gradle
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringChecklistRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringUserRepository.java
- #940 
서버에 스프링 액추에이터 관련 설정을 추가한다.
> [BE] Spring Actuator 관련 설정을 추가한다.

- backend/bang-ggood/build.gradle
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringChecklistRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringUserRepository.java
> [BE] 구현 사항을 DEV 서버로 배포한다.

- .github/workflows/backend-prod-cd.yml
- backend/bang-ggood/build.gradle
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringChecklistRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringUserRepository.java
> [BE/FE] 구현 사항을 PROD 서버에 배포한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
> [BE] 구현 사항을 DEV로 배포한다.

- frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionTemplate.tsx
- frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
- frontend/src/components/NewChecklist/MoveNextButton.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomInfoTemplate.tsx
- frontend/src/components/NewChecklist/Option/OptionTemplate.tsx
- frontend/src/hooks/useMouseDrag.ts
- frontend/src/pages/NewChecklistPage.tsx
- #947 
- 탭 이동 버튼 구현
- **마우스 드래그로 탭 이동하기 구현**
버튼으로도 이동할 수 있고
마우스드래그로도 **100px 이상 드래그 시** 다음/이전 탭으로 이동하게 해놨습니다. (**useMouseDrag 훅** 참고)
탭 문구 & UI 어떻게 생각하시나요?
> [FE] 탭 이동 버튼과 드래그 이동을 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/station/service/ChecklistStationService.java
- #955 
- 좋아요 논리적 삭제
- 지하철 논리적 삭제
> [BE] 체크리스트 삭제 로직에 반영 안 된 로직들을 추가한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
- #965 
보안을 목적으로 쿠키 설정정보 일부를 변경했습니다.
- sameSite : None -> Lax
- Domain : dev.bang-ggood.com -> .bang-ggood.com로 변경
- Path : 요청별로 Path 다르게 지정
> [BE] 쿠키 설정정보를 변경한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
> [BE] DEV와 DEV-BE를 머지한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
> [BE] 쿠키 Path 재지정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
> [BE] 쿠키 저장 문제를 해결한다.

- backend/bang-ggood/build.gradle
- backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/CacheConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheName.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/IntegrationTestSupport.java
- backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
> [BE] 로컬 캐시를 적용한다.

- backend/bang-ggood/build.gradle
- backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordResetService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheName.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestions.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/ComparisonCategorizedQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CategoryRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/IntegrationTestSupport.java
- backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> [BE] 캐시 적용 코드를 포함하여 DEV와 DEV-BE를 머지한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/LoggingAspect.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/dto/BaseLog.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/dto/InfoLog.java
- #987 
로깅 방식 변경 : service의 public 메서드 로깅 → controller 메서드 로깅
포맷 변경 : api 앤드포인트, userId만 저장
> [BE] 로그 포맷과 방식을 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheConfig.java
- #994 
- 운영환경별로 다르게 캐시 TTL 지정
> [BE] 캐시 TTL 시간을 변경한다.

- .github/workflows/backend-dev-cd.yml
> [BE] dev cd 파일을 업데이트 한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
> [BE] 유저 정보 조회 시 userType을 같이 반환한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipal.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipalArgumentResolver.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
- backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
- backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/TestController.java
- backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
- #1004 
- AdminPrinciple 어노테이션
- 아티클 생성, 삭제에 적용
> [BE] 아티클 생성, 삭제를 어드민만 접근하게 한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipal.java
- backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipalArgumentResolver.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
- backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
- backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
- backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/TestController.java
- backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
> [BE] 구현 사항을 DEV 서버에 배포한다.

- .github/workflows/backend-prod-cd.yml
- #1026 
PROD action 파일에서 log 출력 부분을 삭제하였습니다
> [BE] PROD 서버에서 log 파일이 저장되지 않도록 한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
- #1028 
- 아티클 리스트 Cacheable 어노테이션 삭제
- 아티클 삭제시 Cacheable 어노테이션 적용
- 이에 따른 캐시 테스트 변경
> [BE] 아티클 리스트가 캐시되지 않도록 한다.

- backend/bang-ggood/src/main/resources/data.sql
> [BE] sql 파일에 ADMIN 계정을 생성한다.

- backend/bang-ggood/src/main/resources/data.sql
> [BE] dev 배포를 진행한다.

- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
> [FE] 옥탑일 때 인풋 입력 막기

- backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
- backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/station/service/ChecklistStationServiceTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/station/service/SubwayStationServiceTest.java
> [BE] 변경사항을 dev로 병합한다.

- frontend/src/components/ChecklistList/CustomBanner.tsx
- frontend/src/pages/ChecklistListPage.tsx
> [FE] '체크리스트  배너 후버 색상을 넣는다' 를 dev 에 반영한다.

- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
- #1057 
핫픽스.  옥탑일때 층수를 제거하도록함
> feat: 옥탑일때 층수를 제거

- frontend/src/components/NewChecklist/MoveNextButton.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
> [FE] 런칭 후 생긴 버그를 수정한다. 

- frontend/src/components/NewChecklist/MoveNextButton.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
> [FE] 런칭 후 생긴 버그를 수정한다.

- frontend/src/components/NewChecklist/MoveNextButton.tsx
- frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
> [FE] 런칭 후 생긴 버그를 추가 수정한다. 

- backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
- backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
- backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/request/ArticleUpdateRequest.java
- backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/ArticleFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> [BE] 아티클 수정 기능을 구현한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> [BE] 아티클 수정 시 조회가 안되는 문제를 해결한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> [BE] dev 서버에 구현사항을 배포한다.

- .github/workflows/backend-ci.yml
> [BE] CI 빌드 시 캐시 제거한다.

- .github/workflows/backend-ci.yml
> [BE] CI 빌드 시 캐시 제거한다

- .github/workflows/backend-ci.yml
> [BE] CI를 원래 코드로 되돌린다.

- .github/workflows/backend-ci.yml
> [BE] build 오류를 확인하기 위해 로그 레벨 debug로 지정한다.

- .github/workflows/backend-ci.yml
> [BE] CI 파일을 수정한다.

- .github/workflows/backend-ci.yml
> [BE] ci commit depth 설정을 추가한다.

- .github/workflows/backend-ci.yml
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
> [BE] ChecklistRequestV1 임시로 추가

- .github/workflows/backend-ci.yml
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
> [BE] ChecklistRequestV1를 임시로 추가한다.

- .github/workflows/backend-ci.yml
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
> [BE] createChecklistV1 메서드 임시로 추가한다.

- .github/workflows/backend-ci.yml
- .github/workflows/backend-dev-cd.yml
- .github/workflows/backend-prod-cd.yml
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
- backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
- backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
- #1102 
- CD 파일 아티팩트 버전을 v3에서 v4로 업로드한다.
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> [BE] CD 파일 아티팩트 버전을 변경한다.

- frontend/.storybook/main.ts
- frontend/src/components/ChecklistQuestionSelect/QuestionCardList/QuestionCardList.stories.tsx
- #1105
QuestionCardList 하나만 터져있었는데 고쳤습니다.
( 다른것도 터진줄 알았는데 나머지는 터진거 없네요. )
로컬에서 스토리북 데브서버 안켜지길래 고쳤습니다.
> [FE] 터진 스토리북 컴포넌트를 고친다.

- frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
- frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
- frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionTemplate.tsx
- frontend/src/components/_common/Checkbox/Checkbox.tsx
- #1109 
- Reviewer request 기준좀 알려주시와요..
> [FE] 콘솔창에 나타나는 사소한 에러를 수정한다.

- frontend/.storybook/preview.tsx
- frontend/src/components/ArticleList/ArticleCard.stories.tsx
- frontend/src/components/_common/FaceIcon/FaceIcon.stories.tsx
- frontend/src/components/_common/FlexBox/FlexBox.stories.tsx
- frontend/src/components/_common/FlexBox/FlexBox.tsx
- frontend/src/components/_common/Highlight/HighlightText.stories.tsx
- frontend/src/components/_common/Like/LikeButton.stories.tsx
- frontend/src/components/_common/LoadingIndicator/LoadingIndicator.stories.tsx
- frontend/src/components/_common/LoadingIndicator/LoadingIndicator.tsx
- frontend/src/components/_common/LoginButton/EmailLoginButton.stories.tsx
- frontend/src/components/_common/LoginButton/KakaoLoginButton.stories.tsx
- frontend/src/components/_common/Map/RealTimeMap.tsx
- frontend/src/components/_common/Modal/AlertModal/AlertModal.stories.tsx
- frontend/src/components/_common/Modal/LoginModal/LoginModal.stories.tsx
- frontend/src/components/_common/Subway/SubwayStationItem.stories.tsx
- frontend/src/components/_common/Subway/SubwayStations.stories.tsx
- frontend/src/components/_common/Textarea/Textarea.stories.tsx
- frontend/src/components/_common/TopButton/TopButton.stories.tsx
- #1114 
- faceIcon
- flexbox
- hightlight 
- like button
- LoadingIndicator
- login button 
- modal
- subway
- textarea
- top buttob
- article card
> [FE] 스토리북 빠진 컴포넌트를 보충한다. 

- frontend/src/styles/color.ts
- frontend/src/styles/font.ts
- frontend/src/styles/theme.ts
-  #1119 
- color.ts
- font.ts
- 디자인 토큰이 새롭게 만들어진거라, 기존의 theme폴더를 그대로 변경하지 않고, 새롭게 만들었습니다. (수정되지 않음)
- 컴포넌트들은 새롭게 만들어지는 게 아니라, 수정되는 걸로 알고 있습니다. 이제 컴포넌트 수정을 목표로 태스크 가져가면 어떨까 싶습니다.
> [FE] 폰트, 컬러 디자인 토큰 수정한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesResponse.java
- #1153 
`GET /articles` 에 thumbnail 추가
> [BE] 아티클 리스트 조회시 썸네일을 포함한다

- backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesResponse.java
> [BE] 개발 환경으로 코드를 배포한다

- frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
- frontend/src/components/_common/Modal/FocusTrap/FocusTrap.tsx
- frontend/src/components/_common/Textarea/Textarea.tsx
- #1173 
1. 메모 타이핑 포커스 이동이 저장 버튼으로 이동하는 이슈 해결 
2. 메모 폰트 색상 이상 수정 
3. 메모 닫기 아이콘 버튼 커서 추가
> [FE] 메모 작성 버그를 수정한다.

- frontend/src/components/_common/Footer/Footer.tsx
- frontend/src/components/_common/Footer/FooterDefault.tsx
- frontend/src/routers/router.tsx
> [FE] 일단 배포를 위해 빌딩목록을 비활성화한다.

- backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionsResponse.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
- backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/QuestionRepositoryTest.java
- backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> [BE] dev 서버로 dev-be 변경 사항을 배포한다.

- frontend/src/components/_common/Footer/Footer.tsx
- frontend/src/components/_common/Footer/FooterDefault.tsx
- frontend/src/routers/router.tsx
> [FE] 일단 배포를 위해 빌딩목록을 비활성화한다. (#1199)
