frontend/.storybook/main.ts
frontend/package.json
frontend/src/components/Checkbox/Checkbox.stories.tsx
frontend/src/components/Checkbox/Checkbox.tsx
frontend/yarn.lock

- #40 
- 체크박스 기능 구현
- hover 스토리 작성을 위해 'storybook-addon-pseudo-states' addon 의존성 추가
- input 태그에 체크박스속성으로 구현하면 내부체크박스 색상이 파랑으로 고정이며, 브라우저마다 색상이 달라
- 클릭은 input 태그로 다루고 표시는 span태그에 리액트 컴포넌트에 특수문자 v를 넣어 구현하였습니다.
- hover 스토리 작성을 위해 'storybook-addon-pseudo-states' addon 의존성 추가 하였습니다.

공용 체크박스 컴포넌트를 구현한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryQuestionsResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/WrittenCategoryQuestionsResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/WrittenChecklistResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/WrittenQuestionResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
backend/bang-ggood/src/main/java/com/bang_ggood/exception/GlobalExceptionHandler.java
backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/WrittenRoomResponse.java

- #89 
- 작성한 체크리스트를 조회하는 API
- 예외 처리 핸들링에서 서버 로그를 찍어야 합니다
- TODO로 남긴 것은 추후 진행 예정

작성한 체크리스트를 조회하는 API를 구현한다.

---

.github/workflows/backend-cd.yml

-  #117 
- cd 스크립트에 배포 시 로그 파일을 지정해주었다.

배포 서버의 로그가 기록되지 않는 문제를 해결한다.

---

frontend/src/components/common/Footer/Footer.tsx
frontend/src/components/common/Header/Header.tsx

- #113 
직접 클릭해본결과 페이지 이동됩니다.
( 사진은 직접해본결과 되었다는 의미로 올린거니 대충 보셔도됨)
스토리북에서는 Link를 추가함에 따라 클릭시 에러페이지로 이동.
당연히 이렇게될거라 예상은했지만, 
라우터넣어도 별문제없는 스토리도 있길래 추후 해결가능해보임

Footer와 Header 공통 컴포넌트의 icon에 Link, navigator를 추가한다.

---

frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
frontend/src/components/NewChecklist/OptionModal/OptionModalInfoBox.tsx
frontend/src/components/common/Checkbox/Checkbox.tsx
frontend/src/components/common/Tabs/TabContext.tsx
frontend/src/components/common/Tabs/Tabs.stories.tsx
frontend/src/components/common/Tabs/Tabs.tsx
frontend/src/constants/tabs.ts
frontend/src/hooks/useAllSelect.ts
frontend/src/hooks/useChecklistAnswer.ts
frontend/src/pages/NewChecklistPage/NewChecklistBody.tsx
frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
frontend/src/pages/NewChecklistPage/NewChecklistTabContainer.tsx
frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
frontend/src/styles/theme.ts
frontend/src/types/tab.ts

- #171 
(1) 탭을 변경된 디자인으로 리팩토링 하였습니다. 탭의 경우 props drilling 이 심해서 전역 상태인 context로 관리했습니다. 이후 zustand를 도입하면 리팩토링을 할 것 같습니다. 
(2) 일부 setter 함수에서 타입에러를 수정하였습니다. 
ex ) setIsOpen: React.Dispatch<React.SetStateAction<boolean>>;
코멘트로 질문하나 남겨놓겠습니다!
현재 각 탭의 답변 완료 여부를 표시해주는 점 indicator 의 로직을 하고 있습니다.

[FE] 탭을 변경된 디자인으로 리팩토링한다. 

---

frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
frontend/src/pages/ChecklistListPage.tsx
frontend/src/utils/formattedDate.ts

- #173 
- 체크리스트 리스트 페이지 내에 구조분해 할당 추가 
- 시간 포맷팅 추가로 24시간 이내 작성 시 `~시간 전` 이라고 표시

[FE] 체크리스트 리스트 페이지 내 코드 리팩토링 및 시간 포맷팅을 추가한다.

---

frontend/.storybook/main.ts
frontend/webpack.config.js

- #222 
별도의 작업 없이 svgr에 width, height prop으로 전달 시 바로 사용할 수 있게 설정변경
사용법 : 별도의 작업없이 width에 prop으로 넘겨서 사용하면됩니다.
예시로 Soso에 width, height를 넣어 크게만들어준 모습입니다.
.

[FE] svgr의 width, height를 바로 사용할수있게 한다

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java

- #195 
- grade null 값 받을 수 있도록 수정
- 체크리스트 단건 조회 논리적 삭제 도입
- 체크리스트 단건 삭제 논리적 삭제 도입
**CRUD Service 코드 작성 시 유의**하셔야 할 것 같아 언급드립니다
repository에서 조회 및 삭제는 논리적 삭제 및 n+1 문제를 해결하기 위해 
저희가 함수를 재정의하고 query문을 작성해야 하는데요!
컨벤션으로 정했듯 내부적으로 id는 Long이 아닌 long을 쓰기로 했었습니다
이때 JPA에서 사용하는 id는 Long 형태이고, 저희가 재정의하는 함수는 long이에요
따라서 파라미터를 long으로 넘기면 재정의하는 함수가 호출되고 Long으로 넘기면 기존의 JPA 함수가 호출돼요
그 부분을 유의하여 코드를 작성해야 문제가 발생하지 않습니다
=> 혹시 실수가 발생할 수 있을 가능성이 있어서 repository에서 Long을 쓰는 것도 고려해 봐도 좋을 듯해요~

[BE] 체크리스트 삭제 API를 구현한다

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryCustomChecklistQuestionResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryCustomChecklistQuestionsResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java

- #243 
- 커스텀 체크리스트 질문을 전체 조회하는 기능을 구현했습니다.
- isSelected 필드로 커스텀 체크리스트 질문 선택 여부를 반환합니다.
API URL 의견 받습니다~
현재 커스텀 체크리스트 수정 API URL이 `/custom-checklist`이어서 `/custom-checklist/all`로 설정해두긴 했으나,
체크리스트 조회가 아닌 질문 조회이므로 URL에 question이라는 단어가 들어가면 좋을 듯합니다.
`/custom-checklist-questions/all`으로 바꾸는 건 어떨까요??

[BE] 커스텀 체크리스트 질문을 전체 조회한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java

- #325 
질문 목록이 카테고리 아이디 순으로 오지 않는 버그 수정

[BE] 질문 목록 순서를 카테고리 순으로 정렬한다. 

---

frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
frontend/src/components/_common/FormField/FormField.stories.tsx
frontend/src/components/_common/FormField/FormField.tsx
frontend/src/components/_common/Input/Input.tsx
frontend/src/components/_common/Modal/Modal.tsx
frontend/src/components/_common/RadioGroup/RadioContext.ts
frontend/src/components/_common/RadioGroup/RadioGroup.tsx
frontend/src/hooks/useInputs.ts
frontend/src/pages/NewChecklistPage.tsx
frontend/src/store/checklistRoomInfoStore.ts
frontend/src/styles/theme.ts
frontend/src/types/event.ts

- #330 
- 인풋 컴포넌트 UI 변경
- 다음 주소 검색 모달 연결 및 상태 연결 완료 
모달에서 검색한 주소가 상태처리가 되어서 인풋 내부에도 보일 수 있게 작업해놨습니다. 
참고 UI
**추가 변경 사항** 
- 모달 컴포넌트 바뀐 것에 대한 에러가 있어서 수정했습니다. 
- bottom, center, small 모두 확인했으나 혹시 문제있으면 알려주세요 
기존 문제 UI 
바꾼 UI
- 지금 구글 폼 에러 메세지가 작동하고 있는걸까요? 따로 아무런 에러메시지를 확인 할 수 없어서 확인이 필요할거 같습니다.

[FE] 인풋 컴포넌트 UI 를 변경 및 주소 검색 모달을 연결한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java

- #349 
- 회원가입시 디폴트 체크리스트 추가
**논의사항1**
모든 유저에게 보일 예시용 체크리스트여서 처음에는 데이터베이스에 저장해두고 쓰는 방식을 고민했는데요,
다음의 이유들로 힘들다고 판단했습니다.
- 어드민 유저 계정이 필요한데 현재는 CD 과정에서 테이블이 드랍된다. 계속해서 어드민 유저를 추가해주어야 한다.
- 다른 방법으로는 Data.sql에 어드민 계정을 추가할 수 있지만, 어드민 계정이 깃헙에 노출된다. 
그래서 현재는 유저가 회원가입할 때마다 디폴트 체크리스트를 추가하는 방식으로 구현했습니다.
**논의사항2**
체크리스트를 생성하기 위해 AuthService가 ChecklistService와 의존성을 갖게 되었는데요, 하나의 메서드를 사용하기 위해
ChecklistService의 모든 퍼블릭 메서드에 접근할 수 있도록하는 것이 올바른 방법인지 모르겠습니다 🥲

[BE] 회원가입시 디폴트 체크리스트를 추가한다.

---

frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
frontend/src/pages/EditChecklistPage.tsx
frontend/src/store/createFormStore.ts
frontend/webpack.config.js

- #484
체크리스트 수정페이지에서 방이름이 비어있을때 버그를 해결한다.
방이름을 다지웠을때 전송눌러도 N번째방이 채워서 put 보내진다. (edit페이지에는 적용하지않는다.)

[FE] 체크리스트 수정페이지에서 방이름이 비어있을때 버그를 해결한다.

---

frontend/src/components/NewChecklist/SummaryModal/SummaryModal.tsx
frontend/src/hooks/useMutateChecklist.ts
frontend/src/pages/EditChecklistPage.tsx
frontend/src/pages/NewChecklistPage.tsx
frontend/src/types/checklist.ts

- #565 
- 기존 문제였던 인풋 폼 하나의 변동사항이 발생할 때 (인풋이 들어올 때) 페이지 내부에 모든 컴포넌트가 재랜더되는 버그가 있었습니다. 
문제 발생 요인은 페이지에서 포스트 요청을 위해 스토어를 구독하고 있어 발생한 문제로 판단 
해당 스토어를 요청을 보내는 서머리 작성 모달 내부로 이동 시켰습니다. 
**변경 후 랜더되는 모습**

[FE] 폼 입력시 모든 인풋 컴포넌트가 재랜더되는 것을 막는다. 

---

frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
frontend/src/store/checklistRoomInfoStore.ts
frontend/src/store/createFormStore.ts
frontend/webpack.config.js

- #573
- roomInfoStore에서 인자를 응집성있게 받아 사용한다
- BundleAnalyzer 켜져있어서 다시껐습니다. PR전에는 꺼서올려주세요 ~

[FE] roomInfoStore에서 인자를 응집성있게 받아 사용한다

---

frontend/.gitignore
frontend/package.json
frontend/src/apis/config.ts
frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
frontend/src/constants/oAuth.ts
frontend/src/index.tsx
frontend/src/mocks/fixtures/subway.ts
frontend/src/mocks/handlers/subway.ts
frontend/src/routers/router.tsx
frontend/webpack.config.js
frontend/yarn.lock

- #595 
기존에는 빌드 모드 (dev/pro) 를 scripts 로 썼습니다.
또한 모든 환경 변수를 env 한 파일에서 관리를 하는 형태였습니다. 
모드 마다 다른 환경 변수를 써야 할때는, 필요한 곳에서 분기 처리를 해주어야 했습니다.
또한 env 에서 mode 를 바꿔서 api 환경을 설정해줘야 했습니다. 
api 환경을 매번 바꾸기 위해 환경 변수를 직접 건드리는 방법은 위험하고, 번거로워서 다음과 같은 리팩토링을 진행했습니다. 
- 환경 모드 (prod-api / dev-api / msw ) 를 스크립트 명령어로 쉽게 설정할 수 있도록 수정
- 환경 모드에 따라 배포 모드 (production / development) 를 자동으로 설정하도록 수정
환경 변수를 4가지로 분리했습니다. 노션에 해당 파일을 올렸습니다😀
`env` : 공통 환경 변수 파일
`env.msw / env.development / env.production ` : 해당 모드에서만 쓰는 환경 변수 파일 
모드는 `API_ENV` 로 각 파일에 있으며, 각 스크립트 명령어에서 해당 명령어를 전달하는 구조입니다. 
`yarn build` : production 모드로 빌드하는 명령어입니다.
`yarn prod` : production api 를 사용하고, production 모드로 서버를 킵니다.
`yarn dev` :  development api 를 사용하고, development 모드로 서버를 킵니다.
`yarn msw` : msw 를 사용하고, development 모드로 서버를 킵니다.
이제 env 에서 모드를 바꾸지 …

[FE] 환경 변수를 분리하고 모드를 스크립트 명령어로 쓸 수 있도록 수정한다. 

---

frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
frontend/src/components/_common/Textarea/Textarea.tsx

- #590 
- 메모의 커서가 앞으로 가는 버그를 수정하였습니다. 
- 메모의 textarea 에 useEffect를 사용해서 렌더링 된 이후, setSelectionRange 로 커서의 위치를 직접 조작하였습니다.

[FE] 메모 커서가 앞으로가는 버그를 수정한다. 

---

backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java

- #574 
- 지하철 역을 2개 보여주는 기능
- 환승역을 하나로 보여주는 기능

[BE] 가까운 지하철 역을 2개 보여준다.

---

frontend/src/constants/message.ts
frontend/src/constants/system.ts
frontend/src/hooks/query/usePutCustomChecklist.ts
frontend/src/mocks/handlers/checklist.ts
frontend/src/pages/ChecklistCustomPage.tsx

- #636 
기존에는 질문을 아무것도 선택하지 않고 저장을 눌렀을 때 토스트 메세지나 알럿 메세지가 아무것도 나타나지 않아서 사용자에게 화면이 작동하지 않게 보이는 버그가 있었습니다. 
저장 버튼 호출 시 선택된 질문이 0개일시 저장 호출을 막고 에러 토스트를 띄우도록 변경했습니다. 
기존에는 탄스 쿼리를 사용하지 않고 내부에서 호출하는 형식으로 동작하고 있었습니다. 하지만 현재 상위에서 쿼리문에서 에러가 날때 에러 토스트를 띄우고 있어서 400 에러 메세지를 받아도 아무런 메세지를 받지 못했습니다. 
0개 선택 이외에도 네트워크 오류 등으로 인한 에러 메세지를 띄우기 위해 쿼리문으로 리팩토링 진행했습니다.

[FE] 커스텀 질문 페이지에서 0개 선택 후 저장시 생기는 버그를 수정한다. 

---

frontend/src/components/ChecklistDetail/CategoryAccordion.tsx
frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
frontend/src/constants/roomInfo.ts
frontend/src/hooks/query/useGetChecklistQuestionQuery.ts
frontend/src/hooks/useChecklistAnswer.test.ts
frontend/src/hooks/useChecklistAnswer.ts
frontend/src/hooks/useInitialChecklist.ts
frontend/src/hooks/useMutateChecklist.ts
frontend/src/hooks/useNewChecklistTabs.ts
frontend/src/mocks/fixtures/checklistDetail.ts
frontend/src/mocks/fixtures/checklistQuestions.ts
frontend/src/pages/ChecklistDetailPage.tsx
frontend/src/pages/EditChecklistPage.tsx
frontend/src/pages/NewChecklistPage.tsx
frontend/src/store/checklistRoomInfoStore.ts
frontend/src/store/useChecklistCustomStore.ts
frontend/src/store/useChecklistStore.ts
frontend/src/types/checklist.ts
frontend/src/types/room.ts
frontend/webpack.config.js

- #615
- [!] 과도한 청크 끄기 -> 청크가 나눠질 원인이 없는데 40개의 청크로 분리되고있어 원인파악필요.
useChecklistStore에서
validCategory->category 로 명칭변경 하였습니다.
과도한 청크 이슈는 원인파악예정입니다..

[FE] 편집페이지의 기능이 모두 정상 동작하게 만든다

---

frontend/public/index.html
frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
frontend/src/components/NewChecklist/Option/OptionList.tsx

- #633 
- 폰트를 preload 코드를 추가하여 해당 css 코드가 첫 렌더링이 되기 전에 미리 로드되도록 설정하였습니다.
- 전에 반영되지 못한 제이드의 리뷰대로 불필요한 memo 코드를 제거했습니다.

[FE] 폰트를 최적화하는 코드를 추가한다. 

---

frontend/src/components/_common/Header/Header.stories.tsx
frontend/src/components/_common/Header/Header.tsx
frontend/src/components/skeleton/Article/SKArticleDetail.tsx
frontend/src/components/skeleton/Article/SkArticleList.tsx
frontend/src/mocks/fixtures/article.ts
frontend/src/pages/ArticleDetailPage.tsx
frontend/src/types/article.ts

- #656 
추가 요소로 대표이미지가 추가되었습니다. 리스트 내부에도 추가할까 했지만 좁은 아티클 리스트 상 추가할 자리가 없기도 하고 이미지가 그렇게까지 중요한 요소가 아니라서 내부에서만 보여주기로 했습니다. 
**작업한 페이지** 
페이지 작업을 진행하면서 피그마에 나온대로 투명하면서 아래의 요소를 투영할 수 있는 헤더가 필요하여 작업했습니다. 
`isTransparent`요소를 사용해서 투명도를 가진 헤더를 사용할 수 있으며 선택시 헤더 아래 아이템이 투영됩니다. 
자세한 사항은 위에 사진과 스토리북에서 확인하실 수 있습니다.

[FE] 아티클 대표 이미지 요소를 추가한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java

[BE] dev와 dev-be를 합친다.

---

frontend/public/index.html

- #684 
이미지를 preload하였습니다.
사용한 방식 :  index.html의 head태그에 preload를 적용해줬습니다.
검토한 방식
- index.html head태그에 직접 link preload를 넣어주는방식 : image, css 등 다양한 에셋에 적용가능
- webpackPreload 로 자동으로 들어가게하는방식 : js상에서 import하는 경우에만 가능.
처음엔 webpackPreload를 우선적으로 검토하였습니다만,
webpackPreload는 (컴포넌트 js)에서만 적극적으로 활용하고
다른경우엔 일단 전자를 써야한다는 판단을 하여 index.html 방식을 적용했습니다.

[FE] 랜딩페이지의 이미지를 preload한다.

---

frontend/src/components/Answer/AnswerIcon.tsx
frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionAnswers.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
frontend/src/components/_common/Highlight/HighlightText.tsx
frontend/src/components/_common/Tabs/Tab.tsx
frontend/src/components/_common/Tabs/Tabs.tsx
frontend/src/hooks/useChecklistAnswer.ts
frontend/src/hooks/useInitialChecklist.ts

- #672 
- 방 이름 인풋 렌더링 최적화
- 체크리스트 작성할때, 선택한 질문 외에 다른 질문들 렌더링 안되게 최적화
- 선택한 탭 외에 렌더링 안되게 최적화
- 전역 상태를 사용하는 `updateAndToggleAnswer`, `useDefaultRoomName` 를 사용처인 하위 컴포넌트로 내려주어 렌더링이 최대한 작은 범위에서 일어나도록 해주었습니다. 
참고 : zustand 의 상태를 쓰는 컴포넌트들은 memo 를 무시합니다. 이를 최대한 아래에서 사용해주어 최적화를 진행했습니다. 
- 체크리스트 질문 & 답변 컴포넌트가 모두 렌더링 되어, 답변 파트를 `ChecklistQuestionAnswers` 라는 컴포넌트로 나누어주었습니다. `ChecklistQuestionAnswers` 안에서만 store 를 구독하여, 렌더링이 최적화됩니다. 
<video width="200" controls>
<source src="https://github.com/user-attachments/assets/ddf991a0-8daf-4765-af3f-6491db6eb773" type="video/mp4">
</video>
<video width="200" controls>
<source src="https://github.com/user-attachments/assets/de339942-4e52-4f7f-b75a-e8e6eb865913
" type="video/mp4">
</video>

[FE] 체크리스트 렌더링 성능을 최적화한다. 

---

frontend/src/routers/GoogleAnalytics.tsx
frontend/src/routers/router.tsx

[FE] Google Analytics를 레이아웃에 넣어 작동되게 한다.

---

frontend/src/components/ChecklistCustom/QuestionCardList/QuestionCardList.tsx
frontend/src/components/ChecklistCustom/QuestionListTemplate/QuestionListTemplate.tsx
frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
frontend/src/components/NewChecklist/NewChecklistContent.tsx
frontend/src/components/_common/Accordion/Accordion.tsx
frontend/src/components/_common/Modal/Modal.tsx
frontend/src/components/_common/Tabs/Tabs.tsx
frontend/src/components/_common/TipBox/TipBox.tsx
frontend/src/components/_common/layout/Layout.tsx
frontend/src/components/skeleton/Article/SkArticleList.tsx
frontend/src/pages/ArticleDetailPage.tsx
frontend/src/pages/ArticleListPage.tsx
frontend/src/pages/CategoryChoosePage.tsx
frontend/src/pages/ChecklistListPage.tsx
frontend/src/pages/ErrorPage.tsx
frontend/src/pages/LandingPage.tsx
frontend/src/pages/MyPage.tsx

- #726 
- header
- main
- 그 아래 뎁스는 section / article 로 작업하였고, 둘의 구분기준은 '페이지의 맥락에서야 유효한가(section)', '독립적인가(self-contained)' 입니다. 
- footer
국소적 style을 위한 단순 wrapper은 div를 사용
모달은 aside 사용
아래는 이 기준들을 세우는 데 있어서 참고한 글들 중 일부입니다.
[참고한 MDN - article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article)
[참고한 MDN - section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)
[w3school - semantic](https://www.w3schools.com/html/html5_semantic_elements.asp)

[FE] 전반적인 페이지 UI에 적절한 시맨틱 태그를 적용한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProperties.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProvider.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenFixture.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/CookieResolverTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/CookieResolverTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/LoginMockE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java

- #747 
- [토큰 에러 메시지](https://www.notion.so/6b6798854e3e46c9adaac96d33b4ca8f) 적용
- 액세스 토큰과 리프레시 토큰의 에러 메시지를 다르게 하기 위해 리팩토링을 진행했습니다.
- TODO로 남겨둔 부분 리팩토링
- 토큰이 존재하는지 검증하는 부분이 ```1) null 체크, 2) 토큰 유무 체크``` 이렇게 if문내에 존재했는데 실수하기 쉬운 코드라고 생각했습니다. 하나의 메소드에서 검증이 가능하도록 리팩토링했습니다. 
```java
// TODO 리팩토링 전
if (request.getCookies() == null || cookieResolver.isTokenNotExist(request.getCookies())) {
throw new BangggoodException(ExceptionCode.AUTHENTICATION_TOKEN_EMPTY);
}
// 리팩토링 후
public void checkLoginRequired(HttpServletRequest request) {
if (isTokenEmpty(request)) {
throw new BangggoodException(ExceptionCode.AUTHENTICATION_TOKEN_EMPTY);
}
if (isRefreshTokenEmpty(request.getCookies())) {
throw new BangggoodException(ExceptionCode.AUTHENTICATION_REFRESH_TOKEN_EMPTY);
}
}
```
- RefreshToken이 도입되면서 …

[BE] 토큰 관련 코드를 리팩토링한다.

---

.github/workflows/playwright.yml
frontend/README.md
frontend/playwright.config.ts
frontend/src/e2e/newChecklist.spec.ts

- #772 
의존성 설치 캐싱 적용전 (49초)
의존성 설치 캐싱 적용후 (10초 (준비 5초, 본작업 0초, 마무리5초))
나름의 최적화를 했는데도 기본준비시간이 40초이고
작은테스트 하나(3개) 돌아가는데 40초 정도 걸리네요.
브라우저 설치(36초. 아래그림참고) 도 캐싱하려하였으나,
playwright 공식문서에서 이를권장하지 않아 적용하지않았습니다.
기존 : e2e테스트를 돌리려면 환경변수가 필요한데 깃헙액션이 없었음.
변경 :
frontend-msw환경을 만들면 action상에서 secrets변수로 받아올수있기때문에 추가.
액션에서 이걸 받아와 .env 파일로 만들어서 사용.
CI 동작을 확인하면서 작업했어야해서 밑에 깃헙액션 코멘트가 많습니다.

[FE] playwright를 CI 설정한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieResolver.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/RefreshTokenCheckResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/repository/ChecklistStationRepository.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/CookieResolverTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java

- #766 
- 리프레시 토큰의 존재 여부를 반환하는 `/refreshToken/check` API 구현
- 테스트 코드 추가
- 이전 PR에서 테스트 깨지는 부분 수정

[BE] 토큰 확인하는 API를 구현한다.

---

frontend/src/apis/checklist.ts
frontend/src/apis/url.ts
frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
frontend/src/components/_common/Map/AddressMap.tsx
frontend/src/components/_common/Map/RealTimeMap.tsx
frontend/src/constants/map.ts
frontend/src/hooks/useMoveSection.ts
frontend/src/hooks/useMutateChecklist.ts
frontend/src/hooks/useRoomInfoNonValidated.ts
frontend/src/mocks/handlers/subway.ts
frontend/src/pages/ChecklistDetailPage.tsx
frontend/src/pages/NewChecklistPage.tsx
frontend/src/store/roomInfoNonValidatedStore.ts
frontend/src/types/address.ts
frontend/src/types/checklist.ts
frontend/src/utils/createKakaoMapElements.ts

- #776 
- 기존에는 post 데이터에 nearSubways 가 들어갔으나, 이게 빠지게 되었습니다.
- 또한 geolocation 이라는 위도(latitude), 경도(longitude) 값을 추가해야 합니다. 
위처럼 보내는 form 에 대한 변경이 생겨, 이와 관련된 로직을 수정하게 되었습니다. 
(1) 우선 lat,log 등 약어로 쓰고 있던 네이밍을 latitude, longitude 로 수정하였습니다.
(2) `roomInfoNonValidatedStore` 에 주소, 지하철, 위치 등을 저장하는 로직은 유지하되, 필요한 `위치`, `주소` 만 post 할 때 꺼내 사용할 수 있도록 `getFormValues` 라는 메서드를 스토어에 추가해 사용하였습니다. 
아직 post 여부는 확인하지 않았으며, 배포 이후에 확인해보겠습니다!

[FE] 바뀐 포스트 api 의 포맷에 맞게 로직을 수정한다. 

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CategoryRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/QuestionFixture.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/CategoryRepositoryTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java

- #841 
- 카테고리 전달시 질문이 없는 카테고리는 보내지 않는다.
- 예시 ) 아래의 경우 제외하고 보낸다.
```java
{
"categoryId": 5,
"categoryName": "외부",
"questions": []
}
```
- 현재 로직에서 DTO에서 필터링하는 방식도 생각해봤으나 해당 방식으로 작업하면 실수할 가능성이 크다고 생각해 카테고리 조회방식을 바꾸도록 구현했습니다.
- nativeQuery 사용부분은 JPQL 사용으로 변경하고 싶은데 쿼리 실행이 잘 되지 않아 이대로 PR제출합니다. 해결방법있다면 알려주세요!

[BE] 질문이 없는 카테고리는 보내지 않도록 수정한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/QuestionEntity.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CustomChecklistQuestionResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/QuestionResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/SelectedQuestionResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/HighlightRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java

- #855 
- Question, QuestionId 둘 다 저장하는 버전
- Question Enum에 대한 연관관계 제거

[BE] 스키마 변경에 따른 무중단 배포를 진행한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java

- #845 
- 회원가입 시 예시용 체크리스트를 만든다
- 회원가입 시 커스텀 체크리스트 데이터를 초기화한다
- 회원가입 시 탈퇴했던 회원인지 확인한다
카카오 로그인 시에는 최초 가입 회원 가입, 기존 회원 로그인, 탈퇴 회원 재가입 플로우입니다.
일반 회원가입 시에는 최초 가입 회원 가입, 기존 회원 예외 발생, 탈퇴 회원 재가입 플로우입니다.

[BE] 회원가입 시 필요한 로직을 추가한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponseV1.java

- #867 
stations {
stations : []
}
⬇️ 
stations: []

[BE] 체크리스트 조회 시 지하철 역 json 형태를 변경한다.

---

frontend/src/components/_common/Like/LikeButton.tsx
frontend/src/hooks/query/useRefetchGetChecklistList.ts
frontend/src/hooks/query/useToggleLikeQuery.ts

- #902
편집페이지에서 좋아요누르고 뒤로(체크리스트목록)가면,
한스텝씩 계속 늦는현상 해결하였습니다.
그 과정에서 로직이 복잡하다고생각이되어 debounce를 제거하고 공식문서의 구현대로 하였습니다.

[FE] 좋아요 버그를 해결한다.

---

frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
frontend/src/components/ChecklistList/ChecklistCard.tsx
frontend/src/components/_common/Subway/SubwayStations.tsx
frontend/src/components/_common/layout/Layout.tsx
frontend/src/utils/formattedUndefined.ts

- #894 
지난번 QA 진행 중 나온 이야기로 디테일 페이지 가독성이 좋지 않다고 다수의 건의가 나와서 개선 작업 진행했습니다. 
텍스트가 많은 페이지를 감안하여 텍스트를 나열하는 상세 정보 페이지들을 레퍼런스 삼아 개선했습니다. 
아래에 비포 에프터 참조하겠습니다.

[FE] QA 피드백 이후 체크리스트 디테일 페이지 UI/UX 를 개선한다.

---

frontend/playwright.api.config.ts
frontend/playwright.mock.config.ts
frontend/src/apis/checklist.ts

- #908
편집 페이지에 들어갔을 때, 빈인풋은 검증에 어긋나는 입력이 가능해지는 현상 해결
서버에서넘어온 null이 바로 input태그에 입력되었을때생기는현상이라, null값들 없애고 set하게하였습니다.

[FE] 편집 페이지에 들어갔을 때, 검증에 어긋나는 입력이 가능해지는 현상 해결한다.

---

frontend/src/components/Main/ChecklistPreviewCard.tsx

- #908
데이터가없어도 메인페이지에서 선릉역 8분뜨던에러해결

[FE] 메인페이지에 주소가없을때 역이름이 선릉역8분으로 뜨던에러를해결한다.

---

frontend/playwright/tests/api/renderTab.spec.ts
frontend/playwright/tests/mock/postNewChecklist.spec.ts
frontend/src/components/ChecklistQuestionSelect/ChecklistQuestionSelectTabs.tsx
frontend/src/components/ChecklistQuestionSelect/QuestionListTemplate/QuestionListTemplate.tsx
frontend/src/components/EditChecklist/ChecklistContent/EditChecklistContent.tsx
frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
frontend/src/components/EditChecklist/ChecklistTab/EditChecklistTab.tsx
frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
frontend/src/components/_common/errorBoundary/ChecklistTabSuspense.tsx
frontend/src/components/skeleton/Main/SkChecklistSection.tsx
frontend/src/components/skeleton/QuestionSelect/SKQuestionSelectList.tsx
frontend/src/hooks/useInitialChecklist.ts
frontend/src/pages/EditChecklistPage.tsx
frontend/src/pages/NewChecklistPage.tsx
frontend/src/store/useChecklistStore.ts
frontend/src/utils/isSameCategory.ts

- #917 
돌아온 각설이
문제 상황 요약 
**터지는 에러 문제 : 카테고리 ID: 4 를 찾을 수 없습니다.**
해당 문제는 탭을 생성할 때 모든 질문이 다 체크되어있는지 확인하는 과정에서 스토어가 가지고 있는 카테고리와 전달받은 카테고리를 비교하면서 발생합니다. 
아래 사진을 보시면 첫번째가 api 호출 부분입니다. 받아오는 api 에는 4번이 있습니다. 
그런데 두번째 사진의 스토리지를 보시면 4가 없고 3까지만 있는걸 확인하실 수 있습니다. 
| <img width="1161" alt="스크린샷 2024-10-25 오전 1 25 37" src="https://github.com/user-attachments/assets/375f314f-eeb3-4663-be45-c0130cb60304">  |  <img width="1433" alt="스크린샷 2024-10-25 오전 1 30 13" src="https://github.com/user-attachments/assets/3219d69f-c19d-4854-874b-91a8e4094335">   |
|---------------------------|---------------------------|
이 과정을 체크하고 어떻게 하면 이런 문제가 생길까  시나리오가 짜서 시뮬레이션을 돌려봤습니다. 
예상 시나리오 : 
1. 카테고리가 4개인 상태에서 새 체크리스트를 작성하려고 했다. 
2. 작성 중 완료하지 않고 `뒤로가기 버튼` 을 누르지 않은채 빠져나옴 
3. 이후 새로운 링크 혹은 새로운 디바이스, 혹은 url 이동 …

[FE] 탭이 종종 랜더링되지 않고 터지는 버그를 수정한다 + 중복 리셋 로직을 삭제한다

---

frontend/src/apis/user.ts
frontend/src/components/EditChecklist/ChecklistContent/EditChecklistContent.tsx
frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
frontend/src/components/NewChecklist/ChecklistContent.tsx
frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/DepositAndRent.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/RoomContractTerm.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
frontend/src/components/NewChecklist/NewRoomInfoForm/RoomSize.tsx
frontend/src/components/ResetPassword/SendVerificationEmailStep.tsx
frontend/src/components/_common/Tabs/TabContext.tsx
frontend/src/constants/tabs.ts
frontend/src/hooks/useMouseDrag.ts

- #956 
- **변경내용** : 기존 = useMouseDrag가 swipe 핸들러를 window에 걸었음 -> ref를 받아서 ref에 걸도록 변경
```
- 해결하고자 한 문제 : swipe 이벤트 때문에, 주소모달에서의 스와이프에도 탭이동이 되어버림.
- 해결 :  훅의 이벤트 핸들러 범위를 전역(window)대신 좁은 범위로 잡기
```
- **변경내용** : 층수 입력 등 숫자형 방기본정보 입력시 모바일 숫자패드가 뜨도록 반영
```
- 해결하고자 한 문제 : 모바일에서 숫자패드가 뜨게 하고싶다. 그러나 type을 사용하면 stepper가 생기는 등 사이드이펙트가 존재
- 방법 : inputMode="decimal"사용
```
- **변경내용** : (UI) 편집체크리스트의 체크리스트에도 탭이동버튼을 추가
```
- 원인 : 추가/편집이 서로다른컴포넌트를 쓰고있었음. 당시에 '추가'에만 넣어줬었음.
- 방법 : 그냥 추가해줌
```
- post-signup을 fetch->fetcher로 대체하였습니다.

[FE] swipe 기능을 ref를 받아 쓰도록 개선한다

---

frontend/src/apis/user.ts
frontend/src/components/ArticleDetail/ArticleContent.tsx

- #962 
폰트 사이즈가 생각보다 너무 커서 기존 폰트 사이즈 18px -> 14px 로 줄였습니다. 
대신 글자간 간격을 넓혀서 가독성을 챙겨봤습니다.

[FE] 아티클 마크다운 세팅을 변경한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java

[BE] DEV와 DEV-BE를 병합한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestions.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/QuestionsScoreCalculator.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/QuestionsScoreCalculatorTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java

- #974 
`AnsweredQuestions을 먼저 가져오고 Answer.GOOD인 것만 필터링해서 갯수를 확인하면 2번 데이터베이스에 요청을 보내지 않아도 될 것 같아요!
`
불필요한 데이터를 필터링을 위해 다 메모리에 얹고 필터링하는 리소스와 2번 요청을 보내는 리소스 중 어느 것이 더 클까 고민하다가 후자를 택했었는데요! (실제로 테스트 해 보니 거의 차이가 없기도 하였습니다)
하지만 PROD 환경에서는 DB IO를 줄이는 게 베스트인 것 같아 제제의 의견을 반영해 볼게욥 👍
---
```
비교를 위한 계산 로직이 꽤 중요한 도메인이라고 생각하는데 도메인 내부에서 처리하는 건 어떤가요? 🤔
계산 로직을 가진 도메인이 있다면 해당 테스트도 도메인 테스트로 변경할 수 있을 것 같아요~
```
반영하였습니다!
---
체크 된 질문이 없을 때에 null을 반환하는 것도 추가 구현하였습니다!

[BE] 체크리스트 방 비교 기능을 추가 구현한다.

---

.github/workflows/backend-dev-cd.yml
backend/bang-ggood/src/main/resources/console-error-appender.xml
backend/bang-ggood/src/main/resources/console-info-appender.xml
backend/bang-ggood/src/main/resources/console-warn-appender.xml
backend/bang-ggood/src/main/resources/file-error-appender.xml
backend/bang-ggood/src/main/resources/file-info-appender.xml
backend/bang-ggood/src/main/resources/file-warn-appender.xml
backend/bang-ggood/src/main/resources/logback.xml

- #1006 
- 기존에 하나의 파일로 생성하던 로그를 레벨별로 분리
- 파일명 패턴 예시 : /home/ubuntu/logs/warn-%d{yyyy-MM-dd}.log

[BE] 로그레벨별로 파일 분리

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/request/ChecklistStationRequest.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java

- #1021 
geolocation 정보가 room 내부 정보와 중복되어 삭제합니다.
```java
"geolocation" : {
"latitude" : 37.517406150696104,
"longitude" : 127.10333134512422
}
```

[BE] 체크리스트 작성, 수정 API 요청시 중복된 위도, 경도정보를 삭제한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
backend/bang-ggood/src/test/java/com/bang_ggood/station/service/ChecklistStationServiceTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/station/service/SubwayStationServiceTest.java

- #1036
- 지하철역 도보 30분 제한
- 도보 속도 계수 조절 (0.4 -> 0.7)
- 기존 저장된 데이터 처리 방법?

[BE] 지하철 역 응답에 도보 시간 제한을 둔다.

---

frontend/src/components/ArticleDetail/ArticleContent.tsx
frontend/src/components/MyPage/UserFeature.tsx
frontend/src/components/_common/LoginButton/EmailLoginButton.tsx
frontend/src/constants/messages/apiErrorMessage.ts
frontend/src/hooks/query/useAddOAuthUserQuery.ts
frontend/src/hooks/query/useDeleteAccount.ts
frontend/src/hooks/query/useLogoutQuery.ts
frontend/src/hooks/query/usePostOAuthUserQuery.ts
frontend/src/hooks/query/usePostSignInQuery.ts
frontend/src/hooks/query/useUserQuery.ts
frontend/src/hooks/useAutoLogin.ts
frontend/src/hooks/useOAuthLogin.ts
frontend/src/mocks/fixtures/user.ts
frontend/src/pages/AdminPage.tsx
frontend/src/pages/ArticleEditorPage.tsx
frontend/src/pages/SignInPage.tsx
frontend/src/service/amplitude/trackEvent.ts
frontend/src/store/useUserStore.ts
frontend/src/types/user.ts

- #1017 
기존 백엔드로부터 유저 타입을 전달받지 못해서 비밀 어드민 링크를 걸어놓았던 것과 달리 어드민일 시 마이페이지에서 어드민 페이지로 접근 가능하게 버튼 작업을 해놨습니다. 
작업하면서 이전에 꾸준히 이야기 나온 유저 스토어도 함께 제작했습니다. 
스토어 사용으로 엠플리튜드나 이후 유저 로직이 사용될 때 UserQuery 를 호출할 필요 없이 유저 타입으로 분기처리를 하면 될거 같습니다. 
아마 다음 피알에서 마이페이지를 리팩토링할 거 같습니다. 
((기존에는 쿼리 호출 후 에러 바운더리로 게스트 / 유저 모드를 나눠서 작업했습니다. 이젠 그럴필요가 없어짐~~!!)) 
추가적으로 로그아웃/탈퇴할 때 스토어 초기화도 당연히 작업해놨습니당 ~~ !! 
유저 스토어를 만들고 최근 프로젝트를 되돌아 보면서 체크리스트 스토어를 로컬 스토리지로 관리할 필요가 있나 라는 생각이 들고 있습니다. 
zustand persist 기능에서 스토리지를 선택 가능하게 해놨는데 기존에는 디폴트 값인 `localStorage` 를 사용하고 있었지만 이 때문에 탭을 끄고 새로 키더라도 저장되어 발생한 문제들도 여럿 있었던거 같아서 사용자 입력인 체크리스트 폼의 스토리지를 `sessionStorage` 으로 변경하면 어떨까 싶습니다. 
모두 확인하고 정리되면 제가 작업할 수 있을거 같습니다. 
아마 작업하면 유저 스토어는 로컬에 나머지 입력들은 세션으로 저장할거 같습니다. 
찾아본 스토리지 별 사용 예시 
```
**localStorage:**
- 유저의 설정, 인증 토큰, 장기적으로 필요한 데이터 저장.
- 브라우저를 …
```

[FE] 어드민/유저/게스트 구별 로직을 추가하여 유저스토어를 제작한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/station/service/ChecklistStationService.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java

[BE] 체크리스트 지하철 정보 저장 시 위도, 경도가 NULL 인 경우도 허용한다.

---

frontend/src/apis/article.ts
frontend/src/apis/url.ts
frontend/src/components/Admin/Article/AdminArticleCard.tsx
frontend/src/components/Admin/Article/AdminArticleListContainer.tsx
frontend/src/constants/routePath.ts
frontend/src/hooks/query/usePutArticleQuery.ts
frontend/src/hooks/useArticleForm.ts
frontend/src/pages/AdminArticleListPage.tsx
frontend/src/pages/AdminPage.tsx
frontend/src/pages/EditArticlePage.tsx
frontend/src/pages/NewArticlePage.tsx
frontend/src/routers/router.tsx

- #1080 
어드민 페이지에서 아티클 수정 기능을 추가했습니다. 
어드민 페이지에서 수정하기 버튼 클릭 시 아티클 리스트를 볼 수 있고 내부에서 수정하고 싶은 아티클을 선택해서 수정하시면 됩니다~

[FE] 어드민 페이지에 아티클 수정 기능을 추가한다. 

---

frontend/src/components/ChecklistList/ChecklistCard.tsx
frontend/src/components/ChecklistList/CustomBanner.tsx
frontend/src/components/ChecklistList/CustomBannerSection.tsx
frontend/src/components/ChecklistList/LikeFilterButton.tsx
frontend/src/components/_common/Button/Button.tsx
frontend/src/components/_common/FloatingButton/FloatingButton.tsx
frontend/src/components/_common/layout/Layout.tsx
frontend/src/pages/ChecklistListPage.tsx

- #1136 
변경사항 UI 는 아래와 같습니다~
<피그마 디자인>
<작업 페이지>

[FE] 리디자인에 따른 체크리스트 리스트 페이지 레이아웃을 재구성한다.

---

frontend/src/App.tsx
frontend/src/components/RoomCompare/RoomCompareContent.tsx
frontend/src/hooks/query/useGetRoomCategoryDetail.ts

- #1143 
방 비교에서 "방 컨디션"등을 눌렀을 때 뜨는 모달의 데이터를 prefetch하였습니다.
느린네트워크에서는 모달 띄우면 loading을 대기해야해서
네트워크가 느린환경(느린 4G 등)에서는 많이유용할거같네요.

[FE] 방 비교페이지의 모달데이터를 prefetch한다

---

frontend/src/components/_common/Modal/Modal.tsx

- #1155 의 첫번째 항
#1138 에서 ModalInner의 width:100% 를 지웠었는데 그걸 다시 넣어주니까 해결되네요. 
전에는 기존에 내부가 좀 튀어나가는 문제를 고치려고 지웠다고 들었는데 
제 화면에서는 당시 우주가 겪었다고 한 문제가 재현이 안되네요
@tsulocalize 
이 PR코드로
우주 화면에서는 잘 나오는지/내부가 옆으로 튀어나오는지 확인해주시면 감사할거같습니다.

[FE] 모달 위치가 왼쪽으로 쏠리는 현상을 해결한다.

---

backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionsResponse.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/QuestionRepositoryTest.java
backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java

- #1184 
유저가 생성한 질문과 기본 질문(어드민 질문)을 분리해서 response에 담는다.
기존에 있던 `#category` 기반 캐싱이 "유저가 달라질 때", "어드민 질문이 추가/삭제될 때" 문제가 있을 것 같아 제거했습니다.
필요하다고 판단되시면 회의때 논의하면 좋을 것 같습니다.

[BE] 커스텀 체크리스트 질문 목록에서 디폴트 질문을 분리한다.
